---
- name: Ruby dependencies
  yum: name={{item}} state=installed
  sudo: yes
  with_items:
    - autoconf
    - automake
    - bison
    - bzip2
    - curl
    - gcc-c++
    - libffi-devel
    - libtool
    - make
    - openssl-devel
    - patch
    - readline
    - readline-devel
    - wget
    - zlib
    - zlib-devel

- name: Determine whether ruby-install is installed
  stat: path=/usr/local/bin/ruby-install
  register: ruby_install

- name: Download ruby-install
  get_url: url=https://github.com/postmodern/ruby-install/archive/v0.4.3.tar.gz
           dest=/tmp/ruby-install-v0.4.3.tar.gz
  when: not ruby_install.stat.exists

- name: Extract ruby-install
  command: >
    chdir=/tmp
    tar -zxf ruby-install-v0.4.3.tar.gz
    creates=/tmp/ruby-install-0.4.3
  when: not ruby_install.stat.exists

- name: Install ruby-install
  command: >
    chdir=/tmp/ruby-install-0.4.3
    creates=/usr/local/bin/ruby-install
    make install
  sudo: yes
  when: not ruby_install.stat.exists

- name: Install rubies
  command: >
    chdir=/tmp
    ruby-install ruby {{item}} --no-reinstall --src-dir /tmp
  with_items: ruby_versions

- name: Determine whether chruby is installed
  stat: path=/usr/local/share/chruby/chruby.sh
  register: chruby

- name: Download chruby
  get_url: >
    url=https://github.com/postmodern/chruby/archive/v0.3.8.tar.gz
    dest=/tmp/chruby-0.3.8.tar.gz
  when: not chruby.stat.exists

- name: Extract chruby
  command: >
    chdir=/tmp
    tar -zxf chruby-0.3.8.tar.gz
    creates=/tmp/chruby-0.3.8
  when: not chruby.stat.exists

- name: Install chruby
  command: >
    chdir=/tmp/chruby-0.3.8
    creates=/usr/local/share/chruby
    make install
  sudo: yes
  when: not chruby.stat.exists

- name: Set default ruby
  lineinfile: >
    dest=~/.ruby-version
    state=present
    line="ruby-{{ruby_default}}"
    create=yes

- name: Enable chruby
  lineinfile: >
    dest=~/.bash_profile
    state=present
    line="source /usr/local/share/chruby/chruby.sh"

- name: Auto load latest ruby
  lineinfile: >
    dest=~/.bash_profile
    state=present
    line="source /usr/local/share/chruby/auto.sh"
